sudo: false

language: 
 - scala
 - node_js

jdk: 
 - oraclejdk8

scala: 
 - 2.11.7

node_js:
  - "4"

services:
  - mongodb
  - redis

before_install: npm install -g grunt-cli bower

install: 
  - npm install
  - sbt "npm install" "bower install"

after_success: sbt dist

addons:
  artifacts: true
  s3_region: "ap-southeast-1"

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2