web:
  expose:
    - "9000"
  volumes:
   - .:/code
  links:
   - mongo
  image: java
  command: /code/target/universal/golden-cache-1.1.0-SNAPSHOT/bin/golden-cache -Dconfig.resource='application.prod.conf'
mongo:
  image: mongo
  command: mongod --storageEngine=wiredTiger
nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - web